# Generated by Django 4.2.2 on 2023-07-04 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('contact', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('frmale', 'female')], default='male', max_length=20)),
                ('dob', models.DateField()),
                ('profesion', models.CharField(max_length=100)),
                ('last_education', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
